version: '3.8'

services:
  tor-proxy:
    build:
      context: ./infrastructure/tor
      dockerfile: Dockerfile
    container_name: ignoto-tor
    ports:
      - "9050:9050" # Porta padrão do SOCKS5
    volumes:
      - ./infrastructure/tor/torrc:/etc/tor/torrc:ro
    networks:
      - ignoto-net

  ignoto-node:
    build:
      context: ./core-rust
      dockerfile: Dockerfile
    container_name: ignoto-node
    ports:
      - "9944:9944" # Porta RPC do Substrate
    command: ["--dev", "--tmp", "--rpc-external", "--rpc-cors=all"]
    networks:
      - ignoto-net

networks:
  ignoto-net:
    driver: bridge
